INSERT INTO `categoria` (`categoria_nome`) VALUES
('Acessórios para Veículos'),
('Agro, Indústria e Comércio'),
('Animais'),
('Antiguidades'),
('Arte e Artesanato'),
('Bebês'),
('Brinquedos e Hobbies'),
('Calçados e Roupas'),
('Casa, Móveis e Decoração'),
('Celulares e Telefones'),
('Coleções e Comics'),
('Eletrodomésticos'),
('Eletrônicos, Áudio e Vídeo'),
('Esporte e Fitness'),
('Ferramentas e Construção'),
('Filmes e Seriados'),
('Games'),
('Informática'),
('Ingressos'),
('Instrumentos Musicais'),
('Jóias e Relógios'),
('Livros'),
('Música'),
('Saúde e Beleza');